services: 
    - docker

before_install:
    - docker build -f ./docker-react-client/Dockerfile.dev -t client-test ./docker-react-client

script:
    - docker run -e CI=true client-test npm run test -- --coverage

after_success:
    - docker build -t ned4ded/multi-client ./docker-react-client
    - docker build -t ned4ded/multi-server ./docker-server
    - docker build -t ned4ded/multi-worker ./docker-worker
    - docker build -t ned4ded/multi-web-server ./docker-nginx